# Generated by Django 2.1.1 on 2019-03-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='article id')),
                ('article_title', models.CharField(max_length=20, unique=True, verbose_name='article title')),
                ('article_context', models.TextField(verbose_name='article context')),
                ('article_created_time', models.DateTimeField(verbose_name='article created time')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_context', models.TextField(verbose_name='comment context')),
                ('comment_create_time', models.DateTimeField(verbose_name='comment created time')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianshu.Article')),
            ],
        ),
    ]
