# Generated by Django 2.1.1 on 2019-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='user id')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='user name')),
                ('user_tel', models.CharField(max_length=11, unique=True, verbose_name='user telephone')),
                ('user_password', models.CharField(max_length=16, verbose_name='user password')),
            ],
        ),
    ]
