# Generated by Django 2.1.1 on 2019-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='article created time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='comment created time'),
        ),
    ]
