# Generated by Django 2.1.1 on 2019-03-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_img', models.ImageField(upload_to='upload')),
                ('album_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianshu.Article')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=100, verbose_name='user password'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianshu.User'),
        ),
    ]
