# Generated by Django 2.1.1 on 2019-03-07 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jianshu', '0002_auto_20190307_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_img', models.ImageField(upload_to='upload')),
                ('album_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianshu.Article')),
                ('album_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
