# Generated by Django 2.1.1 on 2019-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0003_auto_20190303_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_img',
            field=models.ImageField(upload_to='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
